### ISSUE TITLE
Set proxy setting ?

### ISSUE THREAD

**Issue by macintoshplus** [M6Web/GuzzleHttpBundle#18]
I want set the "proxy" Guzzle setting.

How to do with your bundle ?

**Comment by b-viguier** [comment]
It is not allowed by the [current configuration](https://github.com/M6Web/GuzzleHttpBundle/blob/master/src/DependencyInjection/Configuration.php#L23) :/ But you can make a PR to authorize this option, and it should be forwarded to Guzzle constructor

**Comment by mojoLyon** [comment]
Configuration added with #19
