### ISSUE TITLE
client is not fully configable

### ISSUE THREAD

**Issue by ivoba** [M6Web/GuzzleHttpBundle#38]
Hi,
firstoff: this was the most modern guzzleBundle i could find, so props for that :)

I need to use 
   
 ```
  cookies: true
   verify: false
```

in my Guzzle Client.
This is not possible at the moment since the the clients config is passed via bundle extension and these two options are not respected.

So wouldnt it make sense to just open the client config with ->useAttributeAsKey('name')?

Or how do i set other options to the client?

**Comment by omansour** [comment]
hey @ivoba 

thoses options are request related, I am not sure if its possible to setup this during the client configuration. can you provide an exemple ? 

txs

**Comment by t-geindre** [comment]
I'am having the same issue with authentication parameters. Here is what the client instanciation documentation say:
> All other options passed to the constructor are used as default request options with every request created by the client.

http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client

So we should be able to define all request options in client configuration.
