### ISSUE TITLE
PHP7 compatibility issue

### ISSUE THREAD

**Issue by anacicconi** [M6Web/GuzzleHttpBundle#45]
Hello,

I'm upgrading my project to php7 and I'm using a report generated by phpcs with PHPCompatibility. I got several times the sames error related to the bundle.

I'm using m6web/guzzle-http-bundle 2.0.* Here is an example of the error:

    FILE: ...zle/tests/Guzzle/Tests/Service/Resource/ResourceIteratorTest.php
    ----------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
   3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)

I think that changing the name of the folders and therefore the namespaces directly on Guzzle can fix the error.

Is anybody already using the bundle with php7? Can you give me a feedback?

**Comment by Oliboy50** [comment]
I'm using PHP7 on a lot of projects along with this bundle. I didn't had any issue so far.

The error you've reported seems only affecting a unit test.

I think it's not critical at all. But maybe we should fix this. Thanks!

**Comment by anacicconi** [comment]
Thank you for your feedback @Oliboy50. I have the same error with another bundle. So I think you're right. This may not be very important.

This is the complete list of the files using 'resource' in the namespace if this can help:


FILE: .../src/Guzzle/Service/Resource/AbstractResourceIteratorFactory.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------

FILE: ...src/Guzzle/Service/Resource/CompositeResourceIteratorFactory.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: ...uzzle/src/Guzzle/Service/Resource/MapResourceIteratorFactory.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: ...licis/vendor/guzzle/guzzle/src/Guzzle/Service/Resource/Model.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: ...r/guzzle/guzzle/src/Guzzle/Service/Resource/ResourceIterator.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------

FILE: ...zle/src/Guzzle/Service/Resource/ResourceIteratorApplyBatched.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: ...zle/src/Guzzle/Service/Resource/ResourceIteratorClassFactory.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: ...src/Guzzle/Service/Resource/ResourceIteratorFactoryInterface.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: ...guzzle/src/Guzzle/Service/Resource/ResourceIteratorInterface.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: .../Tests/Service/Resource/CompositeResourceIteratorFactoryTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: ...Guzzle/Tests/Service/Resource/MapResourceIteratorFactoryTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: .../guzzle/guzzle/tests/Guzzle/Tests/Service/Resource/ModelTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: ...zzle/Tests/Service/Resource/ResourceIteratorClassFactoryTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------


FILE: ...zle/tests/Guzzle/Tests/Service/Resource/ResourceIteratorTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 3 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and
   |       | cannot be used to name a class, interface or trait or as part of
   |       | a namespace (T_NAMESPACE)
   |       | (PHPCompatibility.PHP.ForbiddenNamesAsDeclared.Found)
----------------------------------------------------------------------
