### ISSUE TITLE
How to add middleware::mapRequest

### ISSUE THREAD

**Issue by macintoshplus** [M6Web/GuzzleHttpBundle#56]
I use Guzzle middleware with same code:
```
use Psr\Http\Message\RequestInterface;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;
use GuzzleHttp\Client;

$stack = new HandlerStack();
$stack->setHandler(\GuzzleHttp\choose_handler());

$stack->push(Middleware::mapRequest(function (RequestInterface $r) {
    echo 'A';
    return $r;
});
$client = new Client(['handler' => $stack]);
```

How to use the middleware with this bundle ?

**Comment by Oliboy50** [comment]
@macintoshplus hello

this bundle is a simple wrapper around Guzzle clients to ease their integration with the symfony dependency injection

therefore, you can access your Guzzle clients instance (the ones that you've defined in your configuration) and extend them to your need

here is an example of what you're trying to do: https://github.com/M6Web/RequestHeadersForwarderGuzzleBundle/blob/master/src/EventListener/RequestHeadersForwarderListener.php#L68-L77

so, for instance, you can access the handler of your guzzle client like that:
```php
$stack = $myGuzzleClient->getConfig('handler');
```

and, if you want to override the `handler` itself, you can override the parameter `m6web_guzzlehttp.guzzle.handlerstack.class` ( see https://github.com/M6Web/GuzzleHttpBundle/blob/master/src/Resources/config/services.yml#L7 )

**Comment by macintoshplus** [comment]
It's okay,

Tanks you.
